### PR TITLE
Starting to write up results

### PR DESCRIPTION
**Pull request by dangoslen**
I started a doc for observations. Haven't dug in much here, but we can add to it here and use the pull request to facilitate discussion

### CODE REVIEW

**Comment by tirthpatel7498** [comment]
In the doc, you have written that the set-up takes a lot of time. But its not really the case. I think we should change that.

**Comment by tirthpatel7498** [comment]
Also, @dangoslen can you elaborate what do you mean by the following:

" **Start With a Hosted Coding Environment Like [repl.it](https://repl.it) First**
If we would have used [repl.it](https://repl.it) to begin with, we could have made links to them, managing the bugs within them, etc. easier to manage. "

**Comment by dangoslen** [comment]
I mean it would have been easier to manage the experiments since we scrambled to get repl.it links

Feel free to change it as you see fit

**Comment by yash01234** [comment]
We were unnecessarily asking people to install packages. A windows user wouldn't have been able to run to Lua code for example. All this is a waste of time I guess when we can directly use an online IDE

**Comment by dangoslen** [comment]
Thoughts on exporting any graphs/charts to back up our claims?

**Pull request merged**
